---
name: jsonext
description: Enhance Dart JSON manipulation with type safety, error-handling,
  and expressive extensions for seamless data handling.
version: 0.0.4
homepage: https://github.com/chaitanyabsprip/jsonext
repository: https://github.com/chaitanyabsprip/jsonext
issue_tracker: https://github.com/chaitanyabsprip/jsonext/issues

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  very_good_analysis: 5.1.0
